### ISSUE TITLE
runnning a cmd like cat without an argument

### ISSUE THREAD

**Issue by tblaase** [toni-schmitt/minishell#27] opened 2021-12-15 15:38 UTC
**Describe the bug**

**To Reproduce**
1. run `cat`
2. press `ctrl + C`
3. See error
4. run `echo $?`
5. See error

**Expected behavior**
just print a new prompt on a new line and set error code to 130

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85116019/146216441-57a4a7df-6031-4cba-8ad5-0b4ec5c2190f.png)
vs bash
![grafik](https://user-images.githubusercontent.com/85116019/146216701-fec56cfb-5b1c-4602-9ffd-d7c714b1b12d.png)

**Comment by toni-schmitt** [comment] 2021-12-15 17:42
The problem is that set_err_code gets called again after the signal when exitting executor 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/25370820/146237512-930c3213-30e4-47e5-9ad7-4328c1b60313.png">

**Comment by toni-schmitt** [comment] 2021-12-15 17:47
fixed with commit https://github.com/toni-schmitt/minishell/commit/1d5e570a6a0d4ba947e424f8b44d861563a73fb4 now in `set_err_code` now checks with `last_cmd_ctrlc` if the last command was exitted with ctrlc if so, reset the falg and dont change anything

**Closed by toni-schmitt** 2021-12-15 17:47 UTC
Labels: bug
